---
title: "test_build"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(echarts4r)

## Data Barplot -------------------
df_bar_1 <- data.frame(
  Option = c("Acapulco", 
             "Arcelia", 
             "Atlamajalcingo del Monte", 
             "Zihuatanejo", 
             "Taxco de Alarcón", 
             "Ometepec"),  
  percent = c(10,20,30,45,16,34),
  resueltos = c(9,13,15,29,10,22)
)


## Data Radial --------------------------------
df_radial <- data.frame(
  y = c("Sección 0941","Sección 0953","Sección 1204","Sección 1214",
        "Sección 1252","Sección 2702","Sección 0969", "Sección 1194", 
        "Sección 1237", "Sección 1285"),  
  z = c(10,20,30,45,16,34,22,33,5,60)
)
  
  
df_bar_2 <- data.frame(
  Option = c("ANTIOQUIA","CÓRDOBA","CHOCÓ","SUCRE","ATLÁNTICO","BOLÍVAR",
        "MAGDALENA", "CAUCA", "VALLE DEL CAUCA", "CAQUETÁ"),  
  Percent = c(10,20,30,45,16,34,22,33,5,60),
  Resuletos = c(10,20,30,45,16,34,22,33,5,60)
)




## Data Calendar --------------------------
dates <- seq.Date(as.Date("2020-01-01"), as.Date("2021-12-31"), by = "day")

values <- rnorm(length(dates), 20, 6)

year <- data.frame(date = dates, values = values)






## Data Time Series ----------------------
df_timeseries <- data.frame(
  x = seq(50),
  y = round(rnorm(50, 40, 3),1),
  z = round(rnorm(50, 30, 2),1),
  w = round(rnorm(50, 10, 2),1)
)



df_timeseries_test <- data.frame(
  x = c("Enero", "Febrero", "Marzo", 
        "Abril","Mayo","Junio",
        "Julio","Agosto","Septiembre",
        "Octubre","Noviembre","Diciembre"
        ),
  y = c("1","2","3", 
        "10","23","34",
        "39","45","59",
        "69","78","80"
        
        )
)




```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
df_timeseries_test |> 
  e_charts(x) |> 
  e_line(y, smooth = T, name = "Secciones Visitadas" ) |> 
  e_title("")|> 
 e_theme("blue") |>  # theme
  e_legend(left = 0) |> # move legend to the bottom
  e_tooltip(
            trigger = "axis") |> 
  e_datazoom(type = "slider") |> 
 e_toolbox_feature(feature = "dataZoom")
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
df_radial |> 
  e_charts(y) |> 
  e_pie(z, radius = c("30%", "50%")) |> 
  e_title("")|> 
  e_legend(top = 0,type = "scroll")|> 
  e_theme("macarons") 
```

### Chart C

```{r}
x <- 100
plot(x)
```

