---
title: The Rolling Stones Billboard Greatest Hits
author: Antonio Alegría
date: '2021-09-21'
slug: the-rolling-stones-billboard-greatest-hits
categories:
  - infographic
  - R
  - dataviz
  - tidytuesday
tags:
  - dataviz
  - ridgeplot
  - tidytuesday
toc: no
images: ~
---

```{css plot styles, echo = FALSE}

img {
 background: rgb(236, 236, 236);
 box-shadow: rgba(0, 0, 0, 0.4) 0px 2px 4px, rgba(0, 0, 0, 0.3) 0px 7px 13px -3px, rgba(0, 0, 0, 0.2) 0px -3px 0px inset;
 border: 2px solid rgb(200, 200, 200);
 border-radius: 10px;
 transition: all .5s;
 cursor: pointer;
 outline: none;
 
}

img:hover {
  opacity: 1;
  transform: scale(1.2);
  border-radious 20px;
  z-index:1;
}

img:active {
  transform: translateY(-1px);
}

```


# Peaks Position 


The Billboard Hot 100 is the music industry standard record chart in the United States for songs, published weekly by Billboard magazine. Chart rankings are based on sales (physical and digital), radio play, and online streaming in the United States.




```{r include=FALSE}
# 1- Import libraries and dataset -----------------------------------------


library(tidyverse)
library(RColorBrewer)
library(lubridate)
library(ggridges)
library(patchwork)
library(png)
 
billboard <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-09-14/billboard.csv')
theme_set(theme_minimal(base_size = 13
                      ))

billboard_parsed <- billboard %>% 
  mutate(week = mdy(week_id)) %>% 
  select(-week_id)

billboard_TRS <- billboard_parsed %>% 
  filter(performer == "The Rolling Stones") |> 
  mutate(song = fct_reorder(song, peak_position))
  
my_image <- readPNG("rs_logo.png", native = TRUE)


rs_plot <- billboard_TRS |> 
  ggplot(aes(x = peak_position, y = song,
             fill = factor(stat(x))
             )
         )+
  geom_density_ridges_gradient( quantile_lines = TRUE, quantiles = 2,
                                ) +
  scale_fill_viridis_d(direction = -1, guide = "none",option = "F",
                      )+
  labs(title = "                                  Peak Positions in the Billboard Chart",
       subtitle = "",
       y = "",
       x = "Peak Position",
       caption = "Data Source: https://data.world/kcmillersean/billboard-hot-100-1958-2017#
       Chart: antonioalegria.io",
        ) +
  theme(plot.title.position = "plot", 
        plot.title = element_text(face = "bold",
                                  colour = "black",
                                  size = 19, 
                                  hjust = 1),
        axis.title = element_text(face = "bold",
                                  colour = "black"),
        axis.text = element_text(
                                 colour = "black"),
        panel.grid = element_blank(),
        panel.grid.major.y = element_line(colour = "black"),
        plot.caption.position = "plot",
        plot.background = element_rect(fill = "white", # Border color
                                       size = 2)
      
        ) +
  scale_x_continuous(expand = c(0.01, 0), 
                     breaks = c(1, 25, 50, 75, 100))+
  scale_y_discrete(expand = c(0,.1)) 





```



<br>
<br>
```{r message=FALSE, warning=FALSE, echo=FALSE,fig.height=10, fig.width=9}

rs_plot +
inset_element(p = my_image,
              -0.1, 0.7, -1.3, 1.1,
             on_top = T)


```

<br>
<br>